// <auto-generated />
using System;
using CentreAppel.Web.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CentreAppel.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903154935_DateRelanceEnDateHeure")]
    partial class DateRelanceEnDateHeure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.ActionCampagneEntity", b =>
                {
                    b.Property<long>("IdActionsCampagnes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_actions_campagnes");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdActionsCampagnes"));

                    b.Property<string>("CommentaireLibre")
                        .HasColumnType("text")
                        .HasColumnName("commentaire_libre");

                    b.Property<DateOnly?>("DateAchat")
                        .HasColumnType("date")
                        .HasColumnName("date_achat");

                    b.Property<DateTime?>("DateRelance")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_relance");

                    b.Property<DateTime>("DhAction")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_action");

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.Property<int?>("IdCanal")
                        .HasColumnType("integer")
                        .HasColumnName("id_canal");

                    b.Property<long?>("IdCommentaire")
                        .HasColumnType("bigint")
                        .HasColumnName("id_commentaire");

                    b.Property<int>("IdDeroulement")
                        .HasColumnType("integer")
                        .HasColumnName("id_deroulement");

                    b.Property<int?>("IdInteret")
                        .HasColumnType("integer")
                        .HasColumnName("id_interet");

                    b.Property<long>("IdLCampagne")
                        .HasColumnType("bigint")
                        .HasColumnName("id_l_campagne");

                    b.Property<long>("IdOperateur")
                        .HasColumnType("bigint")
                        .HasColumnName("id_operateur");

                    b.Property<long>("IdOperateurCm")
                        .HasColumnType("bigint")
                        .HasColumnName("id_operateur_cm");

                    b.Property<int>("IdTypeContact")
                        .HasColumnType("integer")
                        .HasColumnName("id_type_contact");

                    b.Property<int>("NumAction")
                        .HasColumnType("integer")
                        .HasColumnName("num_action");

                    b.HasKey("IdActionsCampagnes")
                        .HasName("pk_actions_campagne");

                    b.HasIndex("DateRelance")
                        .HasDatabaseName("ix_actions_campagne_date_relance")
                        .HasFilter("date_relance IS NOT NULL");

                    b.HasIndex("IdCanal")
                        .HasDatabaseName("ix_actions_campagne_id_canal");

                    b.HasIndex("IdCommentaire")
                        .HasDatabaseName("ix_actions_campagne_id_commentaire");

                    b.HasIndex("IdDeroulement")
                        .HasDatabaseName("ix_actions_campagne_id_deroulement");

                    b.HasIndex("IdInteret")
                        .HasDatabaseName("ix_actions_campagne_id_interet");

                    b.HasIndex("IdOperateur")
                        .HasDatabaseName("ix_actions_campagne_id_operateur");

                    b.HasIndex("IdOperateurCm")
                        .HasDatabaseName("ix_actions_campagne_id_operateur_cm");

                    b.HasIndex("IdTypeContact")
                        .HasDatabaseName("ix_actions_campagne_id_type_contact");

                    b.HasIndex("IdLCampagne", "NumAction")
                        .IsUnique()
                        .HasDatabaseName("ix_actions_campagne_id_l_campagne_num_action");

                    b.ToTable("actions_campagne", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.CampagneEntity", b =>
                {
                    b.Property<long>("IdCampagne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_campagne");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCampagne"));

                    b.Property<DateOnly>("DateCampagne")
                        .HasColumnType("date")
                        .HasColumnName("date_campagne");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.Property<long>("IdOperateurCm")
                        .HasColumnType("bigint")
                        .HasColumnName("id_operateur_cm");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nom");

                    b.Property<int>("Statut")
                        .HasColumnType("integer")
                        .HasColumnName("statut");

                    b.HasKey("IdCampagne")
                        .HasName("pk_e_campagnes");

                    b.HasIndex("IdOperateurCm")
                        .HasDatabaseName("ix_e_campagnes_id_operateur_cm");

                    b.ToTable("e_campagnes", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.CampagneOperateurEntity", b =>
                {
                    b.Property<long>("IdCampagneOperateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_campagne_operateur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCampagneOperateur"));

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.Property<long>("IdCampagne")
                        .HasColumnType("bigint")
                        .HasColumnName("id_campagne");

                    b.Property<long>("IdOperateur")
                        .HasColumnType("bigint")
                        .HasColumnName("id_operateur");

                    b.HasKey("IdCampagneOperateur")
                        .HasName("pk_campagnes_operateur");

                    b.HasIndex("IdOperateur")
                        .HasDatabaseName("ix_campagnes_operateur_id_operateur");

                    b.HasIndex("IdCampagne", "IdOperateur")
                        .IsUnique()
                        .HasDatabaseName("ix_campagnes_operateur_id_campagne_id_operateur");

                    b.ToTable("campagnes_operateur", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.CanalAchatEntity", b =>
                {
                    b.Property<int>("IdCanal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_canal");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCanal"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.HasKey("IdCanal")
                        .HasName("pk_canaux_achat");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_canaux_achat_code");

                    b.ToTable("canaux_achat", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.ClientHorsContactEntity", b =>
                {
                    b.Property<long>("IdClientsHc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_clients_hc");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdClientsHc"));

                    b.Property<DateOnly>("DateExclusion")
                        .HasColumnType("date")
                        .HasColumnName("date_exclusion");

                    b.Property<decimal>("NumCli")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)")
                        .HasColumnName("num_cli");

                    b.Property<string>("Soc")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("soc");

                    b.HasKey("IdClientsHc")
                        .HasName("pk_clients_hors_contact");

                    b.HasIndex("Soc", "NumCli")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_hors_contact_soc_num_cli");

                    b.ToTable("clients_hors_contact", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.CommentaireCampagneEntity", b =>
                {
                    b.Property<long>("IdCommentaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_commentaire");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCommentaire"));

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.Property<long>("IdCampagne")
                        .HasColumnType("bigint")
                        .HasColumnName("id_campagne");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("libelle");

                    b.HasKey("IdCommentaire")
                        .HasName("pk_commentaires_campagne");

                    b.HasIndex("IdCampagne")
                        .HasDatabaseName("ix_commentaires_campagne_id_campagne");

                    b.ToTable("commentaires_campagne", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.DerniereActionEntity", b =>
                {
                    b.Property<string>("CommentaireLibre")
                        .HasColumnType("text")
                        .HasColumnName("commentaire_libre");

                    b.Property<DateOnly?>("DateAchat")
                        .HasColumnType("date")
                        .HasColumnName("date_achat");

                    b.Property<DateTime?>("DateRelance")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_relance");

                    b.Property<DateTime>("DhAction")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_action");

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.Property<long>("IdActionsCampagnes")
                        .HasColumnType("bigint")
                        .HasColumnName("id_actions_campagnes");

                    b.Property<int?>("IdCanal")
                        .HasColumnType("integer")
                        .HasColumnName("id_canal");

                    b.Property<long?>("IdCommentaire")
                        .HasColumnType("bigint")
                        .HasColumnName("id_commentaire");

                    b.Property<int>("IdDeroulement")
                        .HasColumnType("integer")
                        .HasColumnName("id_deroulement");

                    b.Property<int?>("IdInteret")
                        .HasColumnType("integer")
                        .HasColumnName("id_interet");

                    b.Property<long>("IdLCampagne")
                        .HasColumnType("bigint")
                        .HasColumnName("id_l_campagne");

                    b.Property<long>("IdOperateur")
                        .HasColumnType("bigint")
                        .HasColumnName("id_operateur");

                    b.Property<long>("IdOperateurCm")
                        .HasColumnType("bigint")
                        .HasColumnName("id_operateur_cm");

                    b.Property<int>("IdTypeContact")
                        .HasColumnType("integer")
                        .HasColumnName("id_type_contact");

                    b.Property<int>("NumAction")
                        .HasColumnType("integer")
                        .HasColumnName("num_action");

                    b.ToTable((string)null);

                    b.ToView("v_derniere_action", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.DeroulementEntity", b =>
                {
                    b.Property<int>("IdDeroulement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_deroulement");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDeroulement"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.HasKey("IdDeroulement")
                        .HasName("pk_deroulements");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_deroulements_code");

                    b.ToTable("deroulements", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.InteretClientEntity", b =>
                {
                    b.Property<int>("IdInteret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_interet");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInteret"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.HasKey("IdInteret")
                        .HasName("pk_interets_client");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_interets_client_code");

                    b.ToTable("interets_client", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.LigneCampagneEntity", b =>
                {
                    b.Property<long>("IdLCampagne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_l_campagne");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdLCampagne"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("adresse");

                    b.Property<decimal?>("CaHt")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("ca_ht");

                    b.Property<string>("CodeSoc")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("code_soc");

                    b.Property<string>("Correspondant")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("correspondant");

                    b.Property<string>("Cp")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cp");

                    b.Property<DateOnly?>("DateDernierAchat")
                        .HasColumnType("date")
                        .HasColumnName("date_dernier_achat");

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<long>("IdCampagne")
                        .HasColumnType("bigint")
                        .HasColumnName("id_campagne");

                    b.Property<long?>("IdOperateurAssigne")
                        .HasColumnType("bigint")
                        .HasColumnName("id_operateur_assigne");

                    b.Property<long>("IdOperateurCm")
                        .HasColumnType("bigint")
                        .HasColumnName("id_operateur_cm");

                    b.Property<string>("Langue")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("langue");

                    b.Property<string>("MagasinAffilie")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("magasin_affilie");

                    b.Property<decimal>("NumCli")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)")
                        .HasColumnName("num_cli");

                    b.Property<int>("NumLigne")
                        .HasColumnType("integer")
                        .HasColumnName("num_ligne");

                    b.Property<string>("Pays")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("pays");

                    b.Property<string>("RaisonSociale")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("raison_sociale");

                    b.Property<string>("Rfm")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("rfm");

                    b.Property<string>("Siret")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("siret");

                    b.Property<string>("SousActivite")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("sous_activite");

                    b.Property<string>("Telephone")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("telephone");

                    b.Property<string>("Ville")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("ville");

                    b.HasKey("IdLCampagne")
                        .HasName("pk_l_campagnes");

                    b.HasIndex("IdOperateurAssigne")
                        .HasDatabaseName("ix_l_campagnes_id_operateur_assigne");

                    b.HasIndex("IdOperateurCm")
                        .HasDatabaseName("ix_l_campagnes_id_operateur_cm");

                    b.HasIndex("IdCampagne", "CodeSoc", "NumCli")
                        .IsUnique()
                        .HasDatabaseName("ix_l_campagnes_id_campagne_code_soc_num_cli");

                    b.ToTable("l_campagnes", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.OperateurEntity", b =>
                {
                    b.Property<long>("IdOperateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_operateur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdOperateur"));

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int>("IdRole")
                        .HasColumnType("integer")
                        .HasColumnName("id_role");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("LoginAd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login_ad");

                    b.HasKey("IdOperateur")
                        .HasName("pk_operateurs");

                    b.HasIndex("IdRole")
                        .HasDatabaseName("ix_operateurs_id_role");

                    b.HasIndex("LoginAd")
                        .IsUnique()
                        .HasDatabaseName("ix_operateurs_login_ad");

                    b.ToTable("operateurs", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.ParametreEntity", b =>
                {
                    b.Property<int>("IdParametre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_parametre");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdParametre"));

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("libelle");

                    b.Property<decimal?>("ValeurNum")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valeur_num");

                    b.Property<string>("ValeurTexte")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("valeur_texte");

                    b.HasKey("IdParametre")
                        .HasName("pk_parametres");

                    b.HasIndex("Libelle")
                        .IsUnique()
                        .HasDatabaseName("ix_parametres_libelle");

                    b.ToTable("parametres", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.RoleEntity", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_role");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRole"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.HasKey("IdRole")
                        .HasName("pk_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_code");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.TypeContactEntity", b =>
                {
                    b.Property<int>("IdTypeContact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_type_contact");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeContact"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<bool>("Defaut")
                        .HasColumnType("boolean")
                        .HasColumnName("defaut");

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.HasKey("IdTypeContact")
                        .HasName("pk_types_contact");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_types_contact_code");

                    b.HasIndex("Defaut")
                        .IsUnique()
                        .HasDatabaseName("ix_types_contact_defaut")
                        .HasFilter("defaut = true");

                    b.ToTable("types_contact", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.VerrouLigneEntity", b =>
                {
                    b.Property<long>("IdLCampagne")
                        .HasColumnType("bigint")
                        .HasColumnName("id_l_campagne");

                    b.Property<DateTime>("DhVerrou")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_verrou");

                    b.Property<long>("IdOperateur")
                        .HasColumnType("bigint")
                        .HasColumnName("id_operateur");

                    b.HasKey("IdLCampagne")
                        .HasName("pk_verrous_ligne");

                    b.HasIndex("IdOperateur")
                        .HasDatabaseName("ix_verrous_ligne_id_operateur");

                    b.ToTable("verrous_ligne", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.ActionCampagneEntity", b =>
                {
                    b.HasOne("CentreAppel.Web.Data.Entites.CanalAchatEntity", "Canal")
                        .WithMany()
                        .HasForeignKey("IdCanal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_actions_campagne_canaux_achat_id_canal");

                    b.HasOne("CentreAppel.Web.Data.Entites.CommentaireCampagneEntity", "Commentaire")
                        .WithMany()
                        .HasForeignKey("IdCommentaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_actions_campagne_commentaires_campagne_id_commentaire");

                    b.HasOne("CentreAppel.Web.Data.Entites.DeroulementEntity", "Deroulement")
                        .WithMany()
                        .HasForeignKey("IdDeroulement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_actions_campagne_deroulements_id_deroulement");

                    b.HasOne("CentreAppel.Web.Data.Entites.InteretClientEntity", "Interet")
                        .WithMany()
                        .HasForeignKey("IdInteret")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_actions_campagne_interets_client_id_interet");

                    b.HasOne("CentreAppel.Web.Data.Entites.LigneCampagneEntity", "LigneCampagne")
                        .WithMany()
                        .HasForeignKey("IdLCampagne")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_actions_campagne_l_campagnes_id_l_campagne");

                    b.HasOne("CentreAppel.Web.Data.Entites.OperateurEntity", "Operateur")
                        .WithMany()
                        .HasForeignKey("IdOperateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_actions_campagne_operateurs_id_operateur");

                    b.HasOne("CentreAppel.Web.Data.Entites.OperateurEntity", null)
                        .WithMany()
                        .HasForeignKey("IdOperateurCm")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_actions_campagne_operateurs_id_operateur_cm");

                    b.HasOne("CentreAppel.Web.Data.Entites.TypeContactEntity", "TypeContact")
                        .WithMany()
                        .HasForeignKey("IdTypeContact")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_actions_campagne_types_contact_id_type_contact");

                    b.Navigation("Canal");

                    b.Navigation("Commentaire");

                    b.Navigation("Deroulement");

                    b.Navigation("Interet");

                    b.Navigation("LigneCampagne");

                    b.Navigation("Operateur");

                    b.Navigation("TypeContact");
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.CampagneEntity", b =>
                {
                    b.HasOne("CentreAppel.Web.Data.Entites.OperateurEntity", null)
                        .WithMany()
                        .HasForeignKey("IdOperateurCm")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_e_campagnes_operateurs_id_operateur_cm");
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.CampagneOperateurEntity", b =>
                {
                    b.HasOne("CentreAppel.Web.Data.Entites.CampagneEntity", "Campagne")
                        .WithMany()
                        .HasForeignKey("IdCampagne")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campagnes_operateur_e_campagnes_id_campagne");

                    b.HasOne("CentreAppel.Web.Data.Entites.OperateurEntity", "Operateur")
                        .WithMany()
                        .HasForeignKey("IdOperateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campagnes_operateur_operateurs_id_operateur");

                    b.Navigation("Campagne");

                    b.Navigation("Operateur");
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.CommentaireCampagneEntity", b =>
                {
                    b.HasOne("CentreAppel.Web.Data.Entites.CampagneEntity", "Campagne")
                        .WithMany()
                        .HasForeignKey("IdCampagne")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commentaires_campagne_e_campagnes_id_campagne");

                    b.Navigation("Campagne");
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.LigneCampagneEntity", b =>
                {
                    b.HasOne("CentreAppel.Web.Data.Entites.CampagneEntity", "Campagne")
                        .WithMany()
                        .HasForeignKey("IdCampagne")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_l_campagnes_e_campagnes_id_campagne");

                    b.HasOne("CentreAppel.Web.Data.Entites.OperateurEntity", "OperateurAssigne")
                        .WithMany()
                        .HasForeignKey("IdOperateurAssigne")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_l_campagnes_operateurs_id_operateur_assigne");

                    b.HasOne("CentreAppel.Web.Data.Entites.OperateurEntity", null)
                        .WithMany()
                        .HasForeignKey("IdOperateurCm")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_l_campagnes_operateurs_id_operateur_cm");

                    b.Navigation("Campagne");

                    b.Navigation("OperateurAssigne");
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.OperateurEntity", b =>
                {
                    b.HasOne("CentreAppel.Web.Data.Entites.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operateurs_roles_id_role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.VerrouLigneEntity", b =>
                {
                    b.HasOne("CentreAppel.Web.Data.Entites.LigneCampagneEntity", "LigneCampagne")
                        .WithMany()
                        .HasForeignKey("IdLCampagne")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_verrous_ligne_l_campagnes_id_l_campagne");

                    b.HasOne("CentreAppel.Web.Data.Entites.OperateurEntity", "Operateur")
                        .WithMany()
                        .HasForeignKey("IdOperateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_verrous_ligne_operateurs_id_operateur");

                    b.Navigation("LigneCampagne");

                    b.Navigation("Operateur");
                });
#pragma warning restore 612, 618
        }
    }
}
