// <auto-generated />
using System;
using CentreAppel.Web.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CentreAppel.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260820151427_MakeOperateurAuditable")]
    partial class MakeOperateurAuditable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.OperateurEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int>("IdRole")
                        .HasColumnType("integer")
                        .HasColumnName("id_role");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("LoginAd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login_ad");

                    b.HasKey("Id")
                        .HasName("pk_operateurs");

                    b.HasIndex("IdRole")
                        .HasDatabaseName("ix_operateurs_id_role");

                    b.HasIndex("LoginAd")
                        .IsUnique()
                        .HasDatabaseName("ix_operateurs_login_ad");

                    b.ToTable("operateurs", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.RoleEntity", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_role");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRole"));

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("libelle");

                    b.HasKey("IdRole")
                        .HasName("pk_roles");

                    b.HasIndex("Libelle")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_libelle");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.OperateurEntity", b =>
                {
                    b.HasOne("CentreAppel.Web.Data.Entites.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operateurs_roles_id_role");
                });
#pragma warning restore 612, 618
        }
    }
}
