// <auto-generated />
using System;
using CentreAppel.Web.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CentreAppel.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260820201905_AddCampagnesAndBigIntOperateur")]
    partial class AddCampagnesAndBigIntOperateur
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.OperateurEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int>("IdRole")
                        .HasColumnType("integer")
                        .HasColumnName("id_role");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("LoginAd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login_ad");

                    b.HasKey("Id")
                        .HasName("pk_operateurs");

                    b.HasIndex("IdRole")
                        .HasDatabaseName("ix_operateurs_id_role");

                    b.HasIndex("LoginAd")
                        .IsUnique()
                        .HasDatabaseName("ix_operateurs_login_ad");

                    b.ToTable("operateurs", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.RoleEntity", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_role");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRole"));

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("libelle");

                    b.HasKey("IdRole")
                        .HasName("pk_roles");

                    b.HasIndex("Libelle")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_libelle");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.CampagneEntity", b =>
                {
                    b.Property<long>("IdCampagne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_campagne");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCampagne"));

                    b.Property<DateOnly>("DateCampagne")
                        .HasColumnType("date")
                        .HasColumnName("date_campagne");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.Property<long>("IdOperateurCm")
                        .HasColumnType("bigint")
                        .HasColumnName("id_operateur_cm");

                    b.Property<int>("NbLignes")
                        .HasColumnType("integer")
                        .HasColumnName("nb_lignes");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nom");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut");

                    b.HasKey("IdCampagne")
                        .HasName("pk_e_campagnes");

                    b.HasIndex("IdOperateurCm")
                        .HasDatabaseName("ix_e_campagnes_id_operateur_cm");

                    b.ToTable("e_campagnes", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.LigneCampagneEntity", b =>
                {
                    b.Property<long>("IdLCampagne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_l_campagne");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdLCampagne"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("adresse");

                    b.Property<decimal?>("CaHt")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("ca_ht");

                    b.Property<string>("CodeSoc")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("code_soc");

                    b.Property<string>("Correspondant")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("correspondant");

                    b.Property<string>("Cp")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cp");

                    b.Property<DateOnly?>("DateDernierAchat")
                        .HasColumnType("date")
                        .HasColumnName("date_dernier_achat");

                    b.Property<DateTime>("DhCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_creation");

                    b.Property<DateTime?>("DhModif")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_modif");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<long>("IdCampagne")
                        .HasColumnType("bigint")
                        .HasColumnName("id_campagne");

                    b.Property<long?>("IdOperateurAssigne")
                        .HasColumnType("bigint")
                        .HasColumnName("id_operateur_assigne");

                    b.Property<long>("IdOperateurCm")
                        .HasColumnType("bigint")
                        .HasColumnName("id_operateur_cm");

                    b.Property<string>("Langue")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("langue");

                    b.Property<string>("MagasinAffilie")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("magasin_affilie");

                    b.Property<decimal>("NumCli")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)")
                        .HasColumnName("num_cli");

                    b.Property<int>("NumLigne")
                        .HasColumnType("integer")
                        .HasColumnName("num_ligne");

                    b.Property<string>("Pays")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("pays");

                    b.Property<string>("RaisonSociale")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("raison_sociale");

                    b.Property<string>("Rfm")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("rfm");

                    b.Property<string>("Siret")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("siret");

                    b.Property<string>("SousActivite")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("sous_activite");

                    b.Property<string>("Telephone")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("telephone");

                    b.Property<string>("Ville")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("ville");

                    b.HasKey("IdLCampagne")
                        .HasName("pk_l_campagnes");

                    b.HasIndex("IdOperateurAssigne")
                        .HasDatabaseName("ix_l_campagnes_id_operateur_assigne");

                    b.HasIndex("IdOperateurCm")
                        .HasDatabaseName("ix_l_campagnes_id_operateur_cm");

                    b.HasIndex("IdCampagne", "CodeSoc", "NumCli")
                        .IsUnique()
                        .HasDatabaseName("ix_l_campagnes_id_campagne_code_soc_num_cli");

                    b.ToTable("l_campagnes", (string)null);
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.OperateurEntity", b =>
                {
                    b.HasOne("CentreAppel.Web.Data.Entites.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operateurs_roles_id_role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.CampagneEntity", b =>
                {
                    b.HasOne("CentreAppel.Web.Data.Entites.OperateurEntity", null)
                        .WithMany()
                        .HasForeignKey("IdOperateurCm")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_e_campagnes_operateurs_id_operateur_cm");
                });

            modelBuilder.Entity("CentreAppel.Web.Data.Entites.LigneCampagneEntity", b =>
                {
                    b.HasOne("CentreAppel.Web.Data.Entites.CampagneEntity", "Campagne")
                        .WithMany()
                        .HasForeignKey("IdCampagne")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_l_campagnes_e_campagnes_id_campagne");

                    b.HasOne("CentreAppel.Web.Data.Entites.OperateurEntity", "OperateurAssigne")
                        .WithMany()
                        .HasForeignKey("IdOperateurAssigne")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_l_campagnes_operateurs_id_operateur_assigne");

                    b.HasOne("CentreAppel.Web.Data.Entites.OperateurEntity", null)
                        .WithMany()
                        .HasForeignKey("IdOperateurCm")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_l_campagnes_operateurs_id_operateur_cm");

                    b.Navigation("Campagne");

                    b.Navigation("OperateurAssigne");
                });
#pragma warning restore 612, 618
        }
    }
}
